export const listMappingLocation = {
  jakarta: "cgk",
  yogyakarta: "yia",
  bandung: "bdo",
  surabaya: "sub",
  bali: "dps",
  denpasar: "dps",
  medan: "kno",
  makassar: "upi",
  padang: "pdg",
  semarang: "srg",
  pontianak: "pnk",
  banjarmasin: "bdj",
  palembang: "plm",
  pekanbaru: "pku",
  jambi: "djb",
  manado: "mdc",
  ambon: "amq",
  kupang: "koe",
  kendari: "kdi",
  gorontalo: "gto",
};
